### PR TITLE
add some info (like test dependencies) to Project file

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by yubessy** [comment]
Thank you for your contributions!
Can you explain the reason for this PR?
I would appreciate if you just add some links to official Julia docs explaining these changes.

**Comment by yubessy** [comment]
I realized that Julia 1.0 made some standard libraries to extra  packages. Thanks!
https://julialang.github.io/Pkg.jl/v1/toml-files/

**Comment by KristofferC** [comment]
I noticed this package failing tests on newer Julia versions, and this should fix it.

**Comment by yubessy** [comment]
I see. Thank you again!

**Pull request merged**
